# .NET Core
# Build and test .NET Core projects.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- pipeline

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  projectFile: './src/TheBlueSky.DotNet.Tools.SwiftHash.csproj'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: build
    projects: '$(projectFile)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '$(projectFile)'
- task: NuGetAuthenticate@0
  displayName: 'Authenticate nuget.exe'
  inputs:
    nuGetServiceConnections: 'NuGet connection for dotnet-hash'
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
- script: nuget push TheBlueSky.DotNet.Tools.SwiftHash.*.nupkg -ApiKey $(nuget.apikey) -SkipDuplicate
  displayName: 'Push to NuGet.org'
